// homePage actions
export const DETAILPAGE_GET_START = 'DETAILPAGE_GET_START';
export const DETAILPAGE_GET_SUCCESS = 'DETAILPAGE_GET_SUCCESS';
export const DETAILPAGE_GET_ERROR = 'DETAILPAGE_GET_ERROR';


