// homePage actions
export const DETAILPAGE_GET_START = 'DETAILPAGE_GET_START';
export const DETAILPAGE_GET_SUCCESS = 'DETAILPAGE_GET_SUCCESS';
export const DETAILPAGE_GET_ERROR = 'DETAILPAGE_GET_ERROR';

export const LISTRELEASES_GET_START = 'LISTRELEASES_GET_START';
export const LISTRELEASES_GET_SUCCESS = 'LISTRELEASES_GET_SUCCESS';
export const LISTRELEASES_GET_ERROR = 'LISTRELEASES_GET_ERROR';



